apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  # one pod can contain multiple containers
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
  - name: apache
    image: httpd
