apiVersion: v1
kind: Pod
metadata:
  name: env-nginx
  # one pod can contain multiple containers
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "500"]
    env:
    - name: project
      value: expense
    - name: environment
      value: dev
    - name: component
      value: backend
