apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
    tier: web 
spec:
  type: LoadBalancer
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-np
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    tier: web
  ports:
  - protocol: TCP
    port: 80        # service port
    targetPort: 80   # target port in the pod
    nodePort: 32000  # custom NodePort

